const PACK_EN: Record<string, string> = {
  "pdf-to-image": "Rasterize pages",
  "heic-to-jpg": "Convert to JPG",
  "docx-to-pdf": "Make text PDF",
  "pdf-watermark": "Stamp watermark",
  "pdf-page-numbers": "Add page numbers",
  "pdf-password": "Protect or unlock PDF",
  "pdf-signature": "Stamp signature",
  "background-remover": "Remove background",
  "qr-reader": "Scan QR from image",
  "barcode-generator": "Generate barcode",
  "tip-calculator": "Split the bill",
  "loan-calculator": "Calculate payment",
  "compound-interest": "Project growth",
  "salary-converter": "Convert salary",
  "age-calculator": "Calculate age",
  "fuel-cost": "Estimate fuel cost",
  "xlsx-csv": "Convert spreadsheet",
  "markdown-html": "Convert to HTML",
  "lorem-ipsum": "Generate placeholder",
  "social-counter": "Count characters",
  "strip-html": "Extract text",
  "table-markdown": "Convert table",
  "cron-generator": "Build cron",
  "sql-formatter": "Format SQL",
  "image-text-overlay": "Overlay text",
  "image-blur": "Blur image",
  "png-to-ico": "Build ICO",
  "universal-converter": "Convert file",
  "video-file-info": "Read clip info",
};

const PACK_DE: Record<string, string> = {
  "pdf-to-image": "Seiten rastern",
  "heic-to-jpg": "Nach JPG wandeln",
  "docx-to-pdf": "Text-PDF erzeugen",
  "pdf-watermark": "Wasserzeichen setzen",
  "pdf-page-numbers": "Seitenzahlen setzen",
  "pdf-password": "Verschlüsselung erklären",
  "qr-reader": "QR aus Bild lesen",
  "barcode-generator": "Barcode erzeugen",
  "tip-calculator": "Rechnung teilen",
  "loan-calculator": "Rate berechnen",
  "compound-interest": "Zinsen rechnen",
  "salary-converter": "Gehalt umrechnen",
  "age-calculator": "Alter berechnen",
  "fuel-cost": "Kraftstoff schätzen",
  "xlsx-csv": "Tabelle umwandeln",
  "markdown-html": "Nach HTML wandeln",
  "lorem-ipsum": "Platzhalter erzeugen",
  "social-counter": "Zeichen zählen",
  "strip-html": "Text extrahieren",
  "table-markdown": "Tabelle umwandeln",
  "cron-generator": "Cron bauen",
  "sql-formatter": "SQL formatieren",
  "image-text-overlay": "Text einfügen",
  "image-blur": "Bild unschärfen",
  "png-to-ico": "ICO erzeugen",
  "universal-converter": "Datei umwandeln",
  "video-file-info": "Clip-Info lesen",
};

const PACK_UK: Record<string, string> = {
  "pdf-to-image": "Растеризувати сторінки",
  "heic-to-jpg": "Конвертувати в JPG",
  "docx-to-pdf": "Зробити текстовий PDF",
  "pdf-watermark": "Поставити водяний знак",
  "pdf-page-numbers": "Додати номери сторінок",
  "pdf-password": "Про обмеження шифрування",
  "qr-reader": "Зчитати QR із зображення",
  "barcode-generator": "Створити штрихкод",
  "tip-calculator": "Розділити рахунок",
  "loan-calculator": "Розрахувати платіж",
  "compound-interest": "Порахувати зростання",
  "salary-converter": "Конвертувати зарплату",
  "age-calculator": "Порахувати вік",
  "fuel-cost": "Оцінити пальне",
  "xlsx-csv": "Конвертувати таблицю",
  "markdown-html": "У HTML",
  "lorem-ipsum": "Згенерувати текст",
  "social-counter": "Порахувати символи",
  "strip-html": "Витягти текст",
  "table-markdown": "Конвертувати таблицю",
  "cron-generator": "Зібрати cron",
  "sql-formatter": "Форматувати SQL",
  "image-text-overlay": "Накласти текст",
  "image-blur": "Розмити зображення",
  "png-to-ico": "Зібрати ICO",
  "universal-converter": "Конвертувати файл",
  "video-file-info": "Прочитати кліп",
};

const PACK_PL: Record<string, string> = {
  "pdf-to-image": "Rasteryzuj strony",
  "heic-to-jpg": "Konwertuj do JPG",
  "docx-to-pdf": "Zrób tekstowy PDF",
  "pdf-watermark": "Wstaw znak wodny",
  "pdf-page-numbers": "Dodaj numery stron",
  "pdf-password": "Czytaj limity szyfrowania",
  "qr-reader": "Odczytaj QR z obrazu",
  "barcode-generator": "Wygeneruj kod kreskowy",
  "tip-calculator": "Podziel rachunek",
  "loan-calculator": "Oblicz ratę",
  "compound-interest": "Policz wzrost",
  "salary-converter": "Przelicz pensję",
  "age-calculator": "Oblicz wiek",
  "fuel-cost": "Oszacuj paliwo",
  "xlsx-csv": "Konwertuj arkusz",
  "markdown-html": "Konwertuj do HTML",
  "lorem-ipsum": "Generuj placeholder",
  "social-counter": "Policz znaki",
  "strip-html": "Wyodrębnij tekst",
  "table-markdown": "Konwertuj tabelę",
  "cron-generator": "Zbuduj cron",
  "sql-formatter": "Formatuj SQL",
  "image-text-overlay": "Nałóż tekst",
  "image-blur": "Rozmyj obraz",
  "png-to-ico": "Zbuduj ICO",
  "universal-converter": "Konwertuj plik",
  "video-file-info": "Czytaj info klipu",
};

const PACK_FR: Record<string, string> = {
  "pdf-to-image": "Rasteriser les pages",
  "heic-to-jpg": "Convertir en JPG",
  "docx-to-pdf": "Créer un PDF texte",
  "pdf-watermark": "Apposer un filigrane",
  "pdf-page-numbers": "Ajouter les numéros",
  "pdf-password": "Lire les limites",
  "qr-reader": "Lire le QR de l’image",
  "barcode-generator": "Générer le code-barres",
  "tip-calculator": "Partager l’addition",
  "loan-calculator": "Calculer la mensualité",
  "compound-interest": "Projeter la croissance",
  "salary-converter": "Convertir le salaire",
  "age-calculator": "Calculer l’âge",
  "fuel-cost": "Estimer le carburant",
  "xlsx-csv": "Convertir le tableur",
  "markdown-html": "Convertir en HTML",
  "lorem-ipsum": "Générer le texte",
  "social-counter": "Compter les caractères",
  "strip-html": "Extraire le texte",
  "table-markdown": "Convertir le tableau",
  "cron-generator": "Construire le cron",
  "sql-formatter": "Formater le SQL",
  "image-text-overlay": "Superposer le texte",
  "image-blur": "Flouter l’image",
  "png-to-ico": "Créer l’ICO",
  "universal-converter": "Convertir le fichier",
  "video-file-info": "Lire les infos du clip",
};

const PACK_ES: Record<string, string> = {
  "pdf-to-image": "Rasterizar páginas",
  "heic-to-jpg": "Convertir a JPG",
  "docx-to-pdf": "Crear PDF de texto",
  "pdf-watermark": "Poner marca de agua",
  "pdf-page-numbers": "Añadir números",
  "pdf-password": "Leer límites de cifrado",
  "qr-reader": "Leer QR de la imagen",
  "barcode-generator": "Generar código de barras",
  "tip-calculator": "Dividir la cuenta",
  "loan-calculator": "Calcular la cuota",
  "compound-interest": "Proyectar el crecimiento",
  "salary-converter": "Convertir salario",
  "age-calculator": "Calcular edad",
  "fuel-cost": "Estimar combustible",
  "xlsx-csv": "Convertir hoja",
  "markdown-html": "Convertir a HTML",
  "lorem-ipsum": "Generar texto",
  "social-counter": "Contar caracteres",
  "strip-html": "Extraer texto",
  "table-markdown": "Convertir tabla",
  "cron-generator": "Crear cron",
  "sql-formatter": "Formatear SQL",
  "image-text-overlay": "Superponer texto",
  "image-blur": "Desenfocar imagen",
  "png-to-ico": "Crear ICO",
  "universal-converter": "Convertir archivo",
  "video-file-info": "Leer info del clip",
};

const PACK_IT: Record<string, string> = {
  "pdf-to-image": "Rasterizza pagine",
  "heic-to-jpg": "Converti in JPG",
  "docx-to-pdf": "Crea PDF di testo",
  "pdf-watermark": "Applica filigrana",
  "pdf-page-numbers": "Aggiungi numeri",
  "pdf-password": "Leggi i limiti",
  "qr-reader": "Leggi QR dall’immagine",
  "barcode-generator": "Genera codice a barre",
  "tip-calculator": "Dividi il conto",
  "loan-calculator": "Calcola la rata",
  "compound-interest": "Proietta la crescita",
  "salary-converter": "Converti stipendio",
  "age-calculator": "Calcola età",
  "fuel-cost": "Stima il carburante",
  "xlsx-csv": "Converti foglio",
  "markdown-html": "Converti in HTML",
  "lorem-ipsum": "Genera testo",
  "social-counter": "Conta caratteri",
  "strip-html": "Estrai testo",
  "table-markdown": "Converti tabella",
  "cron-generator": "Crea cron",
  "sql-formatter": "Formatta SQL",
  "image-text-overlay": "Sovrapponi testo",
  "image-blur": "Sfoca immagine",
  "png-to-ico": "Crea ICO",
  "universal-converter": "Converti file",
  "video-file-info": "Leggi info clip",
};

const PACK_PT: Record<string, string> = {
  "pdf-to-image": "Rasterizar páginas",
  "heic-to-jpg": "Converter para JPG",
  "docx-to-pdf": "Criar PDF de texto",
  "pdf-watermark": "Aplicar marca de água",
  "pdf-page-numbers": "Adicionar números",
  "pdf-password": "Ler limites de cifra",
  "qr-reader": "Ler QR da imagem",
  "barcode-generator": "Gerar código de barras",
  "tip-calculator": "Dividir a conta",
  "loan-calculator": "Calcular a prestação",
  "compound-interest": "Projetar o crescimento",
  "salary-converter": "Converter salário",
  "age-calculator": "Calcular idade",
  "fuel-cost": "Estimar combustível",
  "xlsx-csv": "Converter folha",
  "markdown-html": "Converter para HTML",
  "lorem-ipsum": "Gerar texto",
  "social-counter": "Contar caracteres",
  "strip-html": "Extrair texto",
  "table-markdown": "Converter tabela",
  "cron-generator": "Criar cron",
  "sql-formatter": "Formatar SQL",
  "image-text-overlay": "Sobrepor texto",
  "image-blur": "Desfocar imagem",
  "png-to-ico": "Criar ICO",
  "universal-converter": "Converter ficheiro",
  "video-file-info": "Ler info do clipe",
};

const PACK_NL: Record<string, string> = {
  "pdf-to-image": "Pagina's rasteren",
  "heic-to-jpg": "Naar JPG converteren",
  "docx-to-pdf": "Tekst-PDF maken",
  "pdf-watermark": "Watermerk plaatsen",
  "pdf-page-numbers": "Paginanummers zetten",
  "pdf-password": "Encryptielimiet lezen",
  "qr-reader": "QR uit afbeelding",
  "barcode-generator": "Barcode maken",
  "tip-calculator": "Rekening splitsen",
  "loan-calculator": "Termijn berekenen",
  "compound-interest": "Groei berekenen",
  "salary-converter": "Salaris omrekenen",
  "age-calculator": "Leeftijd berekenen",
  "fuel-cost": "Brandstof schatten",
  "xlsx-csv": "Spreadsheet converteren",
  "markdown-html": "Naar HTML omzetten",
  "lorem-ipsum": "Placeholder maken",
  "social-counter": "Tekens tellen",
  "strip-html": "Tekst extraheren",
  "table-markdown": "Tabel omzetten",
  "cron-generator": "Cron bouwen",
  "sql-formatter": "SQL formatteren",
  "image-text-overlay": "Tekst overlay",
  "image-blur": "Afbeelding vervagen",
  "png-to-ico": "ICO bouwen",
  "universal-converter": "Bestand converteren",
  "video-file-info": "Clipinfo lezen",
};

const PACK_TR: Record<string, string> = {
  "pdf-to-image": "Sayfaları rasterle",
  "heic-to-jpg": "JPG’ye dönüştür",
  "docx-to-pdf": "Metin PDF yap",
  "pdf-watermark": "Filigran bas",
  "pdf-page-numbers": "Sayfa numarası ekle",
  "pdf-password": "Şifreleme sınırını oku",
  "qr-reader": "Görselden QR oku",
  "barcode-generator": "Barkod oluştur",
  "tip-calculator": "Hesabı böl",
  "loan-calculator": "Taksiti hesapla",
  "compound-interest": "Büyümeyi hesapla",
  "salary-converter": "Maaşı dönüştür",
  "age-calculator": "Yaşı hesapla",
  "fuel-cost": "Yakıtı tahmin et",
  "xlsx-csv": "Tabloyu dönüştür",
  "markdown-html": "HTML’ye dönüştür",
  "lorem-ipsum": "Metin üret",
  "social-counter": "Karakter say",
  "strip-html": "Metni çıkar",
  "table-markdown": "Tabloyu dönüştür",
  "cron-generator": "Cron oluştur",
  "sql-formatter": "SQL biçimlendir",
  "image-text-overlay": "Metin ekle",
  "image-blur": "Görseli bulanıklaştır",
  "png-to-ico": "ICO oluştur",
  "universal-converter": "Dosyayı dönüştür",
  "video-file-info": "Klip bilgisini oku",
};

const PACK_AR: Record<string, string> = {
  "pdf-to-image": "تحويل الصفحات إلى صور",
  "heic-to-jpg": "تحويل إلى JPG",
  "docx-to-pdf": "إنشاء PDF نصي",
  "pdf-watermark": "وضع علامة مائية",
  "pdf-page-numbers": "إضافة أرقام الصفحات",
  "pdf-password": "حدود التشفير",
  "qr-reader": "قراءة QR من الصورة",
  "barcode-generator": "إنشاء باركود",
  "tip-calculator": "تقسيم الفاتورة",
  "loan-calculator": "حساب القسط",
  "compound-interest": "حساب النمو",
  "salary-converter": "تحويل الراتب",
  "age-calculator": "حساب العمر",
  "fuel-cost": "تقدير الوقود",
  "xlsx-csv": "تحويل الجدول",
  "markdown-html": "تحويل إلى HTML",
  "lorem-ipsum": "توليد نص",
  "social-counter": "عدّ الأحرف",
  "strip-html": "استخراج النص",
  "table-markdown": "تحويل الجدول",
  "cron-generator": "بناء cron",
  "sql-formatter": "تنسيق SQL",
  "image-text-overlay": "إضافة نص",
  "image-blur": "تمويه الصورة",
  "png-to-ico": "بناء ICO",
  "universal-converter": "تحويل الملف",
  "video-file-info": "قراءة معلومات المقطع",
};

const PACK_HE: Record<string, string> = {
  "pdf-to-image": "רסטור דפים",
  "heic-to-jpg": "המר ל-JPG",
  "docx-to-pdf": "צור PDF טקסט",
  "pdf-watermark": "הטבע סימן מים",
  "pdf-page-numbers": "הוסף מספרי עמוד",
  "pdf-password": "קרא מגבלות הצפנה",
  "qr-reader": "סרוק QR מתמונה",
  "barcode-generator": "צור ברקוד",
  "tip-calculator": "פצל את החשבון",
  "loan-calculator": "חשב תשלום",
  "compound-interest": "חשב צמיחה",
  "salary-converter": "המר שכר",
  "age-calculator": "חשב גיל",
  "fuel-cost": "הערך דלק",
  "xlsx-csv": "המר גיליון",
  "markdown-html": "המר ל-HTML",
  "lorem-ipsum": "צור טקסט ממלא",
  "social-counter": "ספור תווים",
  "strip-html": "חלץ טקסט",
  "table-markdown": "המר טבלה",
  "cron-generator": "בנה cron",
  "sql-formatter": "עצב SQL",
  "image-text-overlay": "הוסף טקסט",
  "image-blur": "טשטש תמונה",
  "png-to-ico": "בנה ICO",
  "universal-converter": "המר קובץ",
  "video-file-info": "קרא מידע על קליפ",
};

export const PACK_LABELS: Record<string, Record<string, string>> = {
  en: PACK_EN,
  de: PACK_DE,
  uk: PACK_UK,
  pl: PACK_PL,
  fr: PACK_FR,
  es: PACK_ES,
  it: PACK_IT,
  pt: PACK_PT,
  nl: PACK_NL,
  tr: PACK_TR,
  ar: PACK_AR,
  he: PACK_HE,
};
