import type { Locale } from "@/data/locales";

const EN: Record<string, string> = {
  "merge-pdf": "Merge PDFs",
  "split-pdf": "Split PDF",
  "rotate-pdf": "Rotate PDF",
  "images-to-pdf": "Convert images to PDF",
  "extract-pdf-pages": "Extract pages",
  "pdf-metadata": "Read metadata",
  "reorder-pdf": "Reverse page order",
  "compress-pdf": "Compress PDF",
  "compress-image": "Compress image",
  "resize-image": "Resize image",
  "crop-image": "Crop image",
  "convert-image": "Convert to WebP",
  "image-to-base64": "Encode image",
  "base64-to-image": "Decode image",
  "exif-strip": "Strip metadata",
  "favicon-generator": "Generate favicons",
  "color-extract": "Extract colors",
  "word-counter": "Count words",
  "character-counter": "Count characters",
  "case-converter": "Convert case",
  "remove-duplicate-lines": "Remove duplicates",
  "sort-lines": "Sort lines",
  "slug-generator": "Make slug",
  "whitespace-cleaner": "Clean whitespace",
  "text-statistics": "Analyze text",
  "text-diff": "Compare texts",
  "json-formatter": "Format JSON",
  "json-validator": "Validate JSON",
  "csv-json": "Convert",
  base64: "Encode or decode",
  "url-codec": "Encode or decode",
  "html-entities": "Encode or decode",
  "uuid-generator": "Generate UUIDs",
  "hash-generator": "Hash text",
  "regex-tester": "Test regex",
  "jwt-decoder": "Decode JWT",
  "meta-tag-generator": "Generate tags",
  "robots-txt-generator": "Generate robots.txt",
  "serp-preview": "Preview snippet",
  "hreflang-generator": "Generate hreflang",
  percentage: "Calculate",
  "vat-calculator": "Calculate VAT",
  discount: "Calculate discount",
  "profit-margin": "Calculate margin",
  "bmi-calculator": "Calculate BMI",
  "date-difference": "Calculate difference",
  temperature: "Convert",
  length: "Convert",
  weight: "Convert",
  "data-size": "Convert",
  "hex-rgb-hsl": "Convert color",
  "contrast-checker": "Check contrast",
  "palette-generator": "Generate palette",
  "password-generator": "Generate passwords",
  "qr-generator": "Generate QR code",
  "random-string": "Generate strings",
  "unix-timestamp": "Convert timestamp",
  "timezone-convert": "Convert timezone",
  "xml-formatter": "Format XML",
  "yaml-json": "Convert YAML",
  "sitemap-helper": "Generate sitemap",
  "canonical-helper": "Generate canonical",
  "schema-generator": "Generate schema",
  "og-preview": "Generate Open Graph",
  speed: "Convert",
  area: "Convert",
  volume: "Convert",
  pressure: "Convert",
  energy: "Convert",
  duration: "Convert",
  "gradient-generator": "Generate CSS",
  "url-parser": "Parse URL",
  "query-parser": "Parse query",
  "invoice-math": "Calculate invoice",
  "resume-bullets": "Format bullets",
  "cover-letter-template": "Build template",
  "ics-event": "Create ICS",
};

const DE: Record<string, string> = {
  "merge-pdf": "PDFs zusammenführen",
  "split-pdf": "PDF teilen",
  "rotate-pdf": "PDF drehen",
  "images-to-pdf": "Bilder in PDF",
  "extract-pdf-pages": "Seiten extrahieren",
  "pdf-metadata": "Metadaten lesen",
  "reorder-pdf": "Seiten umkehren",
  "compress-pdf": "PDF komprimieren",
  "compress-image": "Bild komprimieren",
  "resize-image": "Bild skalieren",
  "crop-image": "Bild zuschneiden",
  "convert-image": "Nach WebP wandeln",
  "image-to-base64": "Bild kodieren",
  "base64-to-image": "Bild dekodieren",
  "exif-strip": "Metadaten entfernen",
  "favicon-generator": "Favicons erzeugen",
  "color-extract": "Farben extrahieren",
  "word-counter": "Wörter zählen",
  "character-counter": "Zeichen zählen",
  "case-converter": "Groß-/Kleinschreibung",
  "remove-duplicate-lines": "Duplikate entfernen",
  "sort-lines": "Zeilen sortieren",
  "slug-generator": "Slug erzeugen",
  "whitespace-cleaner": "Leerzeichen bereinigen",
  "text-statistics": "Text analysieren",
  "text-diff": "Texte vergleichen",
  "json-formatter": "JSON formatieren",
  "json-validator": "JSON prüfen",
  "csv-json": "Umwandeln",
  base64: "Kodieren oder dekodieren",
  "url-codec": "Kodieren oder dekodieren",
  "html-entities": "Kodieren oder dekodieren",
  "uuid-generator": "UUIDs erzeugen",
  "hash-generator": "Text hashen",
  "regex-tester": "Regex testen",
  "jwt-decoder": "JWT dekodieren",
  "meta-tag-generator": "Tags erzeugen",
  "robots-txt-generator": "robots.txt erzeugen",
  "serp-preview": "Snippet anzeigen",
  "hreflang-generator": "hreflang erzeugen",
  percentage: "Berechnen",
  "vat-calculator": "MwSt. berechnen",
  discount: "Rabatt berechnen",
  "profit-margin": "Marge berechnen",
  "bmi-calculator": "BMI berechnen",
  "date-difference": "Differenz berechnen",
  temperature: "Umrechnen",
  length: "Umrechnen",
  weight: "Umrechnen",
  "data-size": "Umrechnen",
  "hex-rgb-hsl": "Farbe umrechnen",
  "contrast-checker": "Kontrast prüfen",
  "palette-generator": "Palette erzeugen",
  "password-generator": "Passwörter erzeugen",
  "qr-generator": "QR-Code erzeugen",
  "random-string": "Zeichenketten erzeugen",
  "unix-timestamp": "Zeitstempel umrechnen",
  "timezone-convert": "Zeitzone umrechnen",
  "xml-formatter": "XML formatieren",
  "yaml-json": "YAML umwandeln",
  "sitemap-helper": "Sitemap erzeugen",
  "canonical-helper": "Canonical erzeugen",
  "schema-generator": "Schema erzeugen",
  "og-preview": "Open Graph erzeugen",
  speed: "Umrechnen",
  area: "Umrechnen",
  volume: "Umrechnen",
  pressure: "Umrechnen",
  energy: "Umrechnen",
  duration: "Umrechnen",
  "gradient-generator": "CSS erzeugen",
  "url-parser": "URL zerlegen",
  "query-parser": "Query zerlegen",
  "invoice-math": "Rechnung berechnen",
  "resume-bullets": "Aufzählungen formatieren",
  "cover-letter-template": "Vorlage bauen",
  "ics-event": "ICS erstellen",
};

const UK: Record<string, string> = {
  "merge-pdf": "Об’єднати PDF",
  "split-pdf": "Розділити PDF",
  "rotate-pdf": "Повернути PDF",
  "images-to-pdf": "Зображення в PDF",
  "extract-pdf-pages": "Витягти сторінки",
  "pdf-metadata": "Прочитати метадані",
  "reorder-pdf": "Зворотний порядок",
  "compress-pdf": "Стиснути PDF",
  "compress-image": "Стиснути зображення",
  "resize-image": "Змінити розмір",
  "crop-image": "Обрізати",
  "convert-image": "Конвертувати в WebP",
  "image-to-base64": "Кодувати зображення",
  "base64-to-image": "Декодувати зображення",
  "exif-strip": "Прибрати метадані",
  "favicon-generator": "Згенерувати favicon",
  "color-extract": "Витягти кольори",
  "word-counter": "Порахувати слова",
  "character-counter": "Порахувати символи",
  "case-converter": "Змінити регістр",
  "remove-duplicate-lines": "Прибрати дублікати",
  "sort-lines": "Сортувати рядки",
  "slug-generator": "Зробити slug",
  "whitespace-cleaner": "Очистити пробіли",
  "text-statistics": "Проаналізувати текст",
  "text-diff": "Порівняти тексти",
  "json-formatter": "Форматувати JSON",
  "json-validator": "Перевірити JSON",
  "csv-json": "Конвертувати",
  base64: "Кодувати або декодувати",
  "url-codec": "Кодувати або декодувати",
  "html-entities": "Кодувати або декодувати",
  "uuid-generator": "Згенерувати UUID",
  "hash-generator": "Хешувати текст",
  "regex-tester": "Перевірити regex",
  "jwt-decoder": "Декодувати JWT",
  "meta-tag-generator": "Згенерувати теги",
  "robots-txt-generator": "Згенерувати robots.txt",
  "serp-preview": "Переглянути сніпет",
  "hreflang-generator": "Згенерувати hreflang",
  percentage: "Обчислити",
  "vat-calculator": "Обчислити ПДВ",
  discount: "Обчислити знижку",
  "profit-margin": "Обчислити маржу",
  "bmi-calculator": "Обчислити ІМТ",
  "date-difference": "Обчислити різницю",
  temperature: "Конвертувати",
  length: "Конвертувати",
  weight: "Конвертувати",
  "data-size": "Конвертувати",
  "hex-rgb-hsl": "Конвертувати колір",
  "contrast-checker": "Перевірити контраст",
  "palette-generator": "Згенерувати палітру",
  "password-generator": "Згенерувати паролі",
  "qr-generator": "Згенерувати QR-код",
  "random-string": "Згенерувати рядки",
  "unix-timestamp": "Конвертувати час",
  "timezone-convert": "Змінити часовий пояс",
  "xml-formatter": "Форматувати XML",
  "yaml-json": "Конвертувати YAML",
  "sitemap-helper": "Згенерувати sitemap",
  "canonical-helper": "Згенерувати canonical",
  "schema-generator": "Згенерувати schema",
  "og-preview": "Згенерувати Open Graph",
  speed: "Конвертувати",
  area: "Конвертувати",
  volume: "Конвертувати",
  pressure: "Конвертувати",
  energy: "Конвертувати",
  duration: "Конвертувати",
  "gradient-generator": "Згенерувати CSS",
  "url-parser": "Розібрати URL",
  "query-parser": "Розібрати query",
  "invoice-math": "Обчислити рахунок",
  "resume-bullets": "Форматувати пункти",
  "cover-letter-template": "Зібрати шаблон",
  "ics-event": "Створити ICS",
};

const PL: Record<string, string> = {
  "merge-pdf": "Połącz PDF",
  "split-pdf": "Podziel PDF",
  "rotate-pdf": "Obróć PDF",
  "images-to-pdf": "Obrazy do PDF",
  "extract-pdf-pages": "Wyodrębnij strony",
  "pdf-metadata": "Odczytaj metadane",
  "reorder-pdf": "Odwróć kolejność",
  "compress-pdf": "Kompresuj PDF",
  "compress-image": "Kompresuj obraz",
  "resize-image": "Zmień rozmiar",
  "crop-image": "Przytnij obraz",
  "convert-image": "Konwertuj do WebP",
  "image-to-base64": "Zakoduj obraz",
  "base64-to-image": "Dekoduj obraz",
  "exif-strip": "Usuń metadane",
  "favicon-generator": "Generuj favicon",
  "color-extract": "Wyodrębnij kolory",
  "word-counter": "Policz słowa",
  "character-counter": "Policz znaki",
  "case-converter": "Zmień wielkość liter",
  "remove-duplicate-lines": "Usuń duplikaty",
  "sort-lines": "Sortuj linie",
  "slug-generator": "Utwórz slug",
  "whitespace-cleaner": "Wyczyść spacje",
  "text-statistics": "Analizuj tekst",
  "text-diff": "Porównaj teksty",
  "json-formatter": "Formatuj JSON",
  "json-validator": "Sprawdź JSON",
  "csv-json": "Konwertuj",
  base64: "Koduj lub dekoduj",
  "url-codec": "Koduj lub dekoduj",
  "html-entities": "Koduj lub dekoduj",
  "uuid-generator": "Generuj UUID",
  "hash-generator": "Shashuj tekst",
  "regex-tester": "Testuj regex",
  "jwt-decoder": "Dekoduj JWT",
  "meta-tag-generator": "Generuj tagi",
  "robots-txt-generator": "Generuj robots.txt",
  "serp-preview": "Podgląd snippeta",
  "hreflang-generator": "Generuj hreflang",
  percentage: "Oblicz",
  "vat-calculator": "Oblicz VAT",
  discount: "Oblicz rabat",
  "profit-margin": "Oblicz marżę",
  "bmi-calculator": "Oblicz BMI",
  "date-difference": "Oblicz różnicę",
  temperature: "Przelicz",
  length: "Przelicz",
  weight: "Przelicz",
  "data-size": "Przelicz",
  "hex-rgb-hsl": "Przelicz kolor",
  "contrast-checker": "Sprawdź kontrast",
  "palette-generator": "Generuj paletę",
  "password-generator": "Generuj hasła",
  "qr-generator": "Generuj kod QR",
  "random-string": "Generuj ciągi",
  "unix-timestamp": "Przelicz znacznik",
  "timezone-convert": "Przelicz strefę",
  "xml-formatter": "Formatuj XML",
  "yaml-json": "Konwertuj YAML",
  "sitemap-helper": "Generuj sitemap",
  "canonical-helper": "Generuj canonical",
  "schema-generator": "Generuj schema",
  "og-preview": "Generuj Open Graph",
  speed: "Przelicz",
  area: "Przelicz",
  volume: "Przelicz",
  pressure: "Przelicz",
  energy: "Przelicz",
  duration: "Przelicz",
  "gradient-generator": "Generuj CSS",
  "url-parser": "Parsuj URL",
  "query-parser": "Parsuj query",
  "invoice-math": "Oblicz fakturę",
  "resume-bullets": "Formatuj punkty",
  "cover-letter-template": "Zbuduj szablon",
  "ics-event": "Utwórz ICS",
};

const FR: Record<string, string> = {
  "merge-pdf": "Fusionner les PDF",
  "split-pdf": "Découper le PDF",
  "rotate-pdf": "Pivoter le PDF",
  "images-to-pdf": "Images vers PDF",
  "extract-pdf-pages": "Extraire les pages",
  "pdf-metadata": "Lire les métadonnées",
  "reorder-pdf": "Inverser les pages",
  "compress-pdf": "Compresser le PDF",
  "compress-image": "Compresser l’image",
  "resize-image": "Redimensionner",
  "crop-image": "Recadrer",
  "convert-image": "Convertir en WebP",
  "image-to-base64": "Encoder l’image",
  "base64-to-image": "Décoder l’image",
  "exif-strip": "Retirer les métadonnées",
  "favicon-generator": "Générer des favicons",
  "color-extract": "Extraire les couleurs",
  "word-counter": "Compter les mots",
  "character-counter": "Compter les caractères",
  "case-converter": "Changer la casse",
  "remove-duplicate-lines": "Retirer les doublons",
  "sort-lines": "Trier les lignes",
  "slug-generator": "Créer un slug",
  "whitespace-cleaner": "Nettoyer les espaces",
  "text-statistics": "Analyser le texte",
  "text-diff": "Comparer les textes",
  "json-formatter": "Formater JSON",
  "json-validator": "Valider JSON",
  "csv-json": "Convertir",
  base64: "Encoder ou décoder",
  "url-codec": "Encoder ou décoder",
  "html-entities": "Encoder ou décoder",
  "uuid-generator": "Générer des UUID",
  "hash-generator": "Hacher le texte",
  "regex-tester": "Tester la regex",
  "jwt-decoder": "Décoder le JWT",
  "meta-tag-generator": "Générer les balises",
  "robots-txt-generator": "Générer robots.txt",
  "serp-preview": "Aperçu du snippet",
  "hreflang-generator": "Générer hreflang",
  percentage: "Calculer",
  "vat-calculator": "Calculer la TVA",
  discount: "Calculer la remise",
  "profit-margin": "Calculer la marge",
  "bmi-calculator": "Calculer l’IMC",
  "date-difference": "Calculer l’écart",
  temperature: "Convertir",
  length: "Convertir",
  weight: "Convertir",
  "data-size": "Convertir",
  "hex-rgb-hsl": "Convertir la couleur",
  "contrast-checker": "Vérifier le contraste",
  "palette-generator": "Générer une palette",
  "password-generator": "Générer des mots de passe",
  "qr-generator": "Générer un QR",
  "random-string": "Générer des chaînes",
  "unix-timestamp": "Convertir l’horodatage",
  "timezone-convert": "Convertir le fuseau",
  "xml-formatter": "Formater XML",
  "yaml-json": "Convertir YAML",
  "sitemap-helper": "Générer le sitemap",
  "canonical-helper": "Générer canonical",
  "schema-generator": "Générer le schema",
  "og-preview": "Générer Open Graph",
  speed: "Convertir",
  area: "Convertir",
  volume: "Convertir",
  pressure: "Convertir",
  energy: "Convertir",
  duration: "Convertir",
  "gradient-generator": "Générer le CSS",
  "url-parser": "Analyser l’URL",
  "query-parser": "Analyser la query",
  "invoice-math": "Calculer la facture",
  "resume-bullets": "Formater les puces",
  "cover-letter-template": "Créer le modèle",
  "ics-event": "Créer ICS",
};

const ES: Record<string, string> = {
  "merge-pdf": "Unir PDF",
  "split-pdf": "Dividir PDF",
  "rotate-pdf": "Rotar PDF",
  "images-to-pdf": "Imágenes a PDF",
  "extract-pdf-pages": "Extraer páginas",
  "pdf-metadata": "Leer metadatos",
  "reorder-pdf": "Invertir páginas",
  "compress-pdf": "Comprimir PDF",
  "compress-image": "Comprimir imagen",
  "resize-image": "Redimensionar",
  "crop-image": "Recortar",
  "convert-image": "Convertir a WebP",
  "image-to-base64": "Codificar imagen",
  "base64-to-image": "Decodificar imagen",
  "exif-strip": "Quitar metadatos",
  "favicon-generator": "Generar favicons",
  "color-extract": "Extraer colores",
  "word-counter": "Contar palabras",
  "character-counter": "Contar caracteres",
  "case-converter": "Cambiar mayúsculas",
  "remove-duplicate-lines": "Quitar duplicados",
  "sort-lines": "Ordenar líneas",
  "slug-generator": "Crear slug",
  "whitespace-cleaner": "Limpiar espacios",
  "text-statistics": "Analizar texto",
  "text-diff": "Comparar textos",
  "json-formatter": "Formatear JSON",
  "json-validator": "Validar JSON",
  "csv-json": "Convertir",
  base64: "Codificar o decodificar",
  "url-codec": "Codificar o decodificar",
  "html-entities": "Codificar o decodificar",
  "uuid-generator": "Generar UUID",
  "hash-generator": "Hashear texto",
  "regex-tester": "Probar regex",
  "jwt-decoder": "Decodificar JWT",
  "meta-tag-generator": "Generar etiquetas",
  "robots-txt-generator": "Generar robots.txt",
  "serp-preview": "Vista del snippet",
  "hreflang-generator": "Generar hreflang",
  percentage: "Calcular",
  "vat-calculator": "Calcular IVA",
  discount: "Calcular descuento",
  "profit-margin": "Calcular margen",
  "bmi-calculator": "Calcular IMC",
  "date-difference": "Calcular diferencia",
  temperature: "Convertir",
  length: "Convertir",
  weight: "Convertir",
  "data-size": "Convertir",
  "hex-rgb-hsl": "Convertir color",
  "contrast-checker": "Comprobar contraste",
  "palette-generator": "Generar paleta",
  "password-generator": "Generar contraseñas",
  "qr-generator": "Generar código QR",
  "random-string": "Generar cadenas",
  "unix-timestamp": "Convertir marca de tiempo",
  "timezone-convert": "Convertir zona horaria",
  "xml-formatter": "Formatear XML",
  "yaml-json": "Convertir YAML",
  "sitemap-helper": "Generar sitemap",
  "canonical-helper": "Generar canonical",
  "schema-generator": "Generar schema",
  "og-preview": "Generar Open Graph",
  speed: "Convertir",
  area: "Convertir",
  volume: "Convertir",
  pressure: "Convertir",
  energy: "Convertir",
  duration: "Convertir",
  "gradient-generator": "Generar CSS",
  "url-parser": "Analizar URL",
  "query-parser": "Analizar query",
  "invoice-math": "Calcular factura",
  "resume-bullets": "Formatear viñetas",
  "cover-letter-template": "Crear plantilla",
  "ics-event": "Crear ICS",
};

const IT: Record<string, string> = {
  "merge-pdf": "Unisci PDF",
  "split-pdf": "Dividi PDF",
  "rotate-pdf": "Ruota PDF",
  "images-to-pdf": "Immagini in PDF",
  "extract-pdf-pages": "Estrai pagine",
  "pdf-metadata": "Leggi metadati",
  "reorder-pdf": "Inverti pagine",
  "compress-pdf": "Comprimi PDF",
  "compress-image": "Comprimi immagine",
  "resize-image": "Ridimensiona",
  "crop-image": "Ritaglia",
  "convert-image": "Converti in WebP",
  "image-to-base64": "Codifica immagine",
  "base64-to-image": "Decodifica immagine",
  "exif-strip": "Rimuovi metadati",
  "favicon-generator": "Genera favicon",
  "color-extract": "Estrai colori",
  "word-counter": "Conta parole",
  "character-counter": "Conta caratteri",
  "case-converter": "Cambia maiuscole",
  "remove-duplicate-lines": "Rimuovi duplicati",
  "sort-lines": "Ordina righe",
  "slug-generator": "Crea slug",
  "whitespace-cleaner": "Pulisci spazi",
  "text-statistics": "Analizza testo",
  "text-diff": "Confronta testi",
  "json-formatter": "Formatta JSON",
  "json-validator": "Valida JSON",
  "csv-json": "Converti",
  base64: "Codifica o decodifica",
  "url-codec": "Codifica o decodifica",
  "html-entities": "Codifica o decodifica",
  "uuid-generator": "Genera UUID",
  "hash-generator": "Hash del testo",
  "regex-tester": "Prova regex",
  "jwt-decoder": "Decodifica JWT",
  "meta-tag-generator": "Genera tag",
  "robots-txt-generator": "Genera robots.txt",
  "serp-preview": "Anteprima snippet",
  "hreflang-generator": "Genera hreflang",
  percentage: "Calcola",
  "vat-calculator": "Calcola IVA",
  discount: "Calcola sconto",
  "profit-margin": "Calcola margine",
  "bmi-calculator": "Calcola BMI",
  "date-difference": "Calcola differenza",
  temperature: "Converti",
  length: "Converti",
  weight: "Converti",
  "data-size": "Converti",
  "hex-rgb-hsl": "Converti colore",
  "contrast-checker": "Verifica contrasto",
  "palette-generator": "Genera palette",
  "password-generator": "Genera password",
  "qr-generator": "Genera QR",
  "random-string": "Genera stringhe",
  "unix-timestamp": "Converti timestamp",
  "timezone-convert": "Converti fuso",
  "xml-formatter": "Formatta XML",
  "yaml-json": "Converti YAML",
  "sitemap-helper": "Genera sitemap",
  "canonical-helper": "Genera canonical",
  "schema-generator": "Genera schema",
  "og-preview": "Genera Open Graph",
  speed: "Converti",
  area: "Converti",
  volume: "Converti",
  pressure: "Converti",
  energy: "Converti",
  duration: "Converti",
  "gradient-generator": "Genera CSS",
  "url-parser": "Analizza URL",
  "query-parser": "Analizza query",
  "invoice-math": "Calcola fattura",
  "resume-bullets": "Formatta elenco",
  "cover-letter-template": "Crea modello",
  "ics-event": "Crea ICS",
};

const PT: Record<string, string> = {
  "merge-pdf": "Juntar PDFs",
  "split-pdf": "Dividir PDF",
  "rotate-pdf": "Rodar PDF",
  "images-to-pdf": "Imagens para PDF",
  "extract-pdf-pages": "Extrair páginas",
  "pdf-metadata": "Ler metadados",
  "reorder-pdf": "Inverter páginas",
  "compress-pdf": "Comprimir PDF",
  "compress-image": "Comprimir imagem",
  "resize-image": "Redimensionar",
  "crop-image": "Recortar",
  "convert-image": "Converter para WebP",
  "image-to-base64": "Codificar imagem",
  "base64-to-image": "Descodificar imagem",
  "exif-strip": "Remover metadados",
  "favicon-generator": "Gerar favicons",
  "color-extract": "Extrair cores",
  "word-counter": "Contar palavras",
  "character-counter": "Contar caracteres",
  "case-converter": "Alterar maiúsculas",
  "remove-duplicate-lines": "Remover duplicados",
  "sort-lines": "Ordenar linhas",
  "slug-generator": "Criar slug",
  "whitespace-cleaner": "Limpar espaços",
  "text-statistics": "Analisar texto",
  "text-diff": "Comparar textos",
  "json-formatter": "Formatar JSON",
  "json-validator": "Validar JSON",
  "csv-json": "Converter",
  base64: "Codificar ou descodificar",
  "url-codec": "Codificar ou descodificar",
  "html-entities": "Codificar ou descodificar",
  "uuid-generator": "Gerar UUID",
  "hash-generator": "Gerar hash",
  "regex-tester": "Testar regex",
  "jwt-decoder": "Descodificar JWT",
  "meta-tag-generator": "Gerar tags",
  "robots-txt-generator": "Gerar robots.txt",
  "serp-preview": "Pré-visualizar snippet",
  "hreflang-generator": "Gerar hreflang",
  percentage: "Calcular",
  "vat-calculator": "Calcular IVA",
  discount: "Calcular desconto",
  "profit-margin": "Calcular margem",
  "bmi-calculator": "Calcular IMC",
  "date-difference": "Calcular diferença",
  temperature: "Converter",
  length: "Converter",
  weight: "Converter",
  "data-size": "Converter",
  "hex-rgb-hsl": "Converter cor",
  "contrast-checker": "Verificar contraste",
  "palette-generator": "Gerar paleta",
  "password-generator": "Gerar palavras-passe",
  "qr-generator": "Gerar código QR",
  "random-string": "Gerar cadeias",
  "unix-timestamp": "Converter carimbo",
  "timezone-convert": "Converter fuso",
  "xml-formatter": "Formatar XML",
  "yaml-json": "Converter YAML",
  "sitemap-helper": "Gerar sitemap",
  "canonical-helper": "Gerar canonical",
  "schema-generator": "Gerar schema",
  "og-preview": "Gerar Open Graph",
  speed: "Converter",
  area: "Converter",
  volume: "Converter",
  pressure: "Converter",
  energy: "Converter",
  duration: "Converter",
  "gradient-generator": "Gerar CSS",
  "url-parser": "Analisar URL",
  "query-parser": "Analisar query",
  "invoice-math": "Calcular fatura",
  "resume-bullets": "Formatar tópicos",
  "cover-letter-template": "Criar modelo",
  "ics-event": "Criar ICS",
};

const NL: Record<string, string> = {
  "merge-pdf": "PDF's samenvoegen",
  "split-pdf": "PDF splitsen",
  "rotate-pdf": "PDF draaien",
  "images-to-pdf": "Afbeeldingen naar PDF",
  "extract-pdf-pages": "Pagina's extraheren",
  "pdf-metadata": "Metadata lezen",
  "reorder-pdf": "Volgorde omkeren",
  "compress-pdf": "PDF comprimeren",
  "compress-image": "Afbeelding comprimeren",
  "resize-image": "Formaat wijzigen",
  "crop-image": "Bijsnijden",
  "convert-image": "Naar WebP converteren",
  "image-to-base64": "Afbeelding encoderen",
  "base64-to-image": "Afbeelding decoderen",
  "exif-strip": "Metadata verwijderen",
  "favicon-generator": "Favicons maken",
  "color-extract": "Kleuren extraheren",
  "word-counter": "Woorden tellen",
  "character-counter": "Tekens tellen",
  "case-converter": "Hoofdletters wijzigen",
  "remove-duplicate-lines": "Duplicaten verwijderen",
  "sort-lines": "Regels sorteren",
  "slug-generator": "Slug maken",
  "whitespace-cleaner": "Spaties opschonen",
  "text-statistics": "Tekst analyseren",
  "text-diff": "Teksten vergelijken",
  "json-formatter": "JSON formatteren",
  "json-validator": "JSON valideren",
  "csv-json": "Converteren",
  base64: "Coderen of decoderen",
  "url-codec": "Coderen of decoderen",
  "html-entities": "Coderen of decoderen",
  "uuid-generator": "UUID's genereren",
  "hash-generator": "Tekst hashen",
  "regex-tester": "Regex testen",
  "jwt-decoder": "JWT decoderen",
  "meta-tag-generator": "Tags genereren",
  "robots-txt-generator": "robots.txt genereren",
  "serp-preview": "Snippet bekijken",
  "hreflang-generator": "hreflang genereren",
  percentage: "Berekenen",
  "vat-calculator": "Btw berekenen",
  discount: "Korting berekenen",
  "profit-margin": "Marge berekenen",
  "bmi-calculator": "BMI berekenen",
  "date-difference": "Verschil berekenen",
  temperature: "Omrekenen",
  length: "Omrekenen",
  weight: "Omrekenen",
  "data-size": "Omrekenen",
  "hex-rgb-hsl": "Kleur omrekenen",
  "contrast-checker": "Contrast controleren",
  "palette-generator": "Palet maken",
  "password-generator": "Wachtwoorden maken",
  "qr-generator": "QR-code maken",
  "random-string": "Strings maken",
  "unix-timestamp": "Tijdstempel omrekenen",
  "timezone-convert": "Tijdzone omrekenen",
  "xml-formatter": "XML formatteren",
  "yaml-json": "YAML converteren",
  "sitemap-helper": "Sitemap maken",
  "canonical-helper": "Canonical maken",
  "schema-generator": "Schema maken",
  "og-preview": "Open Graph maken",
  speed: "Omrekenen",
  area: "Omrekenen",
  volume: "Omrekenen",
  pressure: "Omrekenen",
  energy: "Omrekenen",
  duration: "Omrekenen",
  "gradient-generator": "CSS maken",
  "url-parser": "URL ontleden",
  "query-parser": "Query ontleden",
  "invoice-math": "Factuur berekenen",
  "resume-bullets": "Opsomming formatteren",
  "cover-letter-template": "Sjabloon bouwen",
  "ics-event": "ICS maken",
};

const TR: Record<string, string> = {
  "merge-pdf": "PDF birleştir",
  "split-pdf": "PDF böl",
  "rotate-pdf": "PDF döndür",
  "images-to-pdf": "Görselleri PDF yap",
  "extract-pdf-pages": "Sayfaları çıkar",
  "pdf-metadata": "Metaveriyi oku",
  "reorder-pdf": "Sayfa sırasını ters çevir",
  "compress-pdf": "PDF sıkıştır",
  "compress-image": "Görseli sıkıştır",
  "resize-image": "Boyutlandır",
  "crop-image": "Kırp",
  "convert-image": "WebP’ye dönüştür",
  "image-to-base64": "Görseli kodla",
  "base64-to-image": "Görseli çöz",
  "exif-strip": "Metaveriyi sil",
  "favicon-generator": "Favicon oluştur",
  "color-extract": "Renkleri çıkar",
  "word-counter": "Kelimeleri say",
  "character-counter": "Karakterleri say",
  "case-converter": "Büyük/küçük harf",
  "remove-duplicate-lines": "Yinelemeleri sil",
  "sort-lines": "Satırları sırala",
  "slug-generator": "Slug oluştur",
  "whitespace-cleaner": "Boşlukları temizle",
  "text-statistics": "Metni analiz et",
  "text-diff": "Metinleri karşılaştır",
  "json-formatter": "JSON biçimlendir",
  "json-validator": "JSON doğrula",
  "csv-json": "Dönüştür",
  base64: "Kodla veya çöz",
  "url-codec": "Kodla veya çöz",
  "html-entities": "Kodla veya çöz",
  "uuid-generator": "UUID üret",
  "hash-generator": "Metni hashle",
  "regex-tester": "Regex dene",
  "jwt-decoder": "JWT çöz",
  "meta-tag-generator": "Etiket üret",
  "robots-txt-generator": "robots.txt üret",
  "serp-preview": "Snippet önizle",
  "hreflang-generator": "hreflang üret",
  percentage: "Hesapla",
  "vat-calculator": "KDV hesapla",
  discount: "İndirim hesapla",
  "profit-margin": "Marj hesapla",
  "bmi-calculator": "BMI hesapla",
  "date-difference": "Farkı hesapla",
  temperature: "Dönüştür",
  length: "Dönüştür",
  weight: "Dönüştür",
  "data-size": "Dönüştür",
  "hex-rgb-hsl": "Rengi dönüştür",
  "contrast-checker": "Kontrastı kontrol et",
  "palette-generator": "Palet oluştur",
  "password-generator": "Parola oluştur",
  "qr-generator": "QR kod oluştur",
  "random-string": "Dize oluştur",
  "unix-timestamp": "Zaman damgasını dönüştür",
  "timezone-convert": "Saat dilimini dönüştür",
  "xml-formatter": "XML biçimlendir",
  "yaml-json": "YAML dönüştür",
  "sitemap-helper": "Sitemap oluştur",
  "canonical-helper": "Canonical oluştur",
  "schema-generator": "Schema oluştur",
  "og-preview": "Open Graph oluştur",
  speed: "Dönüştür",
  area: "Dönüştür",
  volume: "Dönüştür",
  pressure: "Dönüştür",
  energy: "Dönüştür",
  duration: "Dönüştür",
  "gradient-generator": "CSS oluştur",
  "url-parser": "URL çözümle",
  "query-parser": "Query çözümle",
  "invoice-math": "Fatura hesapla",
  "resume-bullets": "Madde işaretlerini biçimlendir",
  "cover-letter-template": "Şablon oluştur",
  "ics-event": "ICS oluştur",
};

const AR: Record<string, string> = {
  "merge-pdf": "دمج PDF",
  "split-pdf": "تقسيم PDF",
  "rotate-pdf": "تدوير PDF",
  "images-to-pdf": "تحويل الصور إلى PDF",
  "extract-pdf-pages": "استخراج الصفحات",
  "pdf-metadata": "قراءة البيانات الوصفية",
  "reorder-pdf": "عكس ترتيب الصفحات",
  "compress-pdf": "ضغط PDF",
  "compress-image": "ضغط الصورة",
  "resize-image": "تغيير الحجم",
  "crop-image": "قص الصورة",
  "convert-image": "تحويل إلى WebP",
  "image-to-base64": "ترميز الصورة",
  "base64-to-image": "فك ترميز الصورة",
  "exif-strip": "إزالة البيانات الوصفية",
  "favicon-generator": "إنشاء أيقونات الموقع",
  "color-extract": "استخراج الألوان",
  "word-counter": "عدّ الكلمات",
  "character-counter": "عدّ الأحرف",
  "case-converter": "تحويل حالة الأحرف",
  "remove-duplicate-lines": "إزالة التكرارات",
  "sort-lines": "ترتيب الأسطر",
  "slug-generator": "إنشاء slug",
  "whitespace-cleaner": "تنظيف المسافات",
  "text-statistics": "تحليل النص",
  "text-diff": "مقارنة النصوص",
  "json-formatter": "تنسيق JSON",
  "json-validator": "التحقق من JSON",
  "csv-json": "تحويل",
  base64: "ترميز أو فك ترميز",
  "url-codec": "ترميز أو فك ترميز",
  "html-entities": "ترميز أو فك ترميز",
  "uuid-generator": "إنشاء UUID",
  "hash-generator": "تجزئة النص",
  "regex-tester": "اختبار التعبير النمطي",
  "jwt-decoder": "فك JWT",
  "meta-tag-generator": "إنشاء الوسوم",
  "robots-txt-generator": "إنشاء robots.txt",
  "serp-preview": "معاينة المقتطف",
  "hreflang-generator": "إنشاء hreflang",
  percentage: "احسب",
  "vat-calculator": "احسب الضريبة",
  discount: "احسب الخصم",
  "profit-margin": "احسب الهامش",
  "bmi-calculator": "احسب مؤشر الكتلة",
  "date-difference": "احسب الفرق",
  temperature: "حوّل",
  length: "حوّل",
  weight: "حوّل",
  "data-size": "حوّل",
  "hex-rgb-hsl": "حوّل اللون",
  "contrast-checker": "افحص التباين",
  "palette-generator": "أنشئ لوحة",
  "password-generator": "أنشئ كلمات مرور",
  "qr-generator": "أنشئ رمز QR",
  "random-string": "أنشئ سلاسل",
  "unix-timestamp": "حوّل الطابع الزمني",
  "timezone-convert": "حوّل المنطقة الزمنية",
  "xml-formatter": "تنسيق XML",
  "yaml-json": "تحويل YAML",
  "sitemap-helper": "إنشاء خريطة الموقع",
  "canonical-helper": "إنشاء canonical",
  "schema-generator": "إنشاء schema",
  "og-preview": "إنشاء Open Graph",
  speed: "حوّل",
  area: "حوّل",
  volume: "حوّل",
  pressure: "حوّل",
  energy: "حوّل",
  duration: "حوّل",
  "gradient-generator": "إنشاء CSS",
  "url-parser": "تحليل الرابط",
  "query-parser": "تحليل الاستعلام",
  "invoice-math": "احسب الفاتورة",
  "resume-bullets": "تنسيق النقاط",
  "cover-letter-template": "بناء القالب",
  "ics-event": "إنشاء ICS",
};

const HE: Record<string, string> = {
  "merge-pdf": "מיזוג PDF",
  "split-pdf": "פיצול PDF",
  "rotate-pdf": "סיבוב PDF",
  "images-to-pdf": "תמונות ל-PDF",
  "extract-pdf-pages": "חילוץ עמודים",
  "pdf-metadata": "קריאת מטא-נתונים",
  "reorder-pdf": "היפוך סדר עמודים",
  "compress-pdf": "דחיסת PDF",
  "compress-image": "דחיסת תמונה",
  "resize-image": "שינוי גודל",
  "crop-image": "חיתוך תמונה",
  "convert-image": "המרה ל-WebP",
  "image-to-base64": "קידוד תמונה",
  "base64-to-image": "פענוח תמונה",
  "exif-strip": "הסרת מטא-נתונים",
  "favicon-generator": "יצירת פביקונים",
  "color-extract": "חילוץ צבעים",
  "word-counter": "ספירת מילים",
  "character-counter": "ספירת תווים",
  "case-converter": "שינוי רישיות",
  "remove-duplicate-lines": "הסרת כפילויות",
  "sort-lines": "מיון שורות",
  "slug-generator": "יצירת slug",
  "whitespace-cleaner": "ניקוי רווחים",
  "text-statistics": "ניתוח טקסט",
  "text-diff": "השוואת טקסטים",
  "json-formatter": "עיצוב JSON",
  "json-validator": "אימות JSON",
  "csv-json": "המרה",
  base64: "קידוד או פענוח",
  "url-codec": "קידוד או פענוח",
  "html-entities": "קידוד או פענוח",
  "uuid-generator": "יצירת UUID",
  "hash-generator": "גיבוב טקסט",
  "regex-tester": "בדיקת regex",
  "jwt-decoder": "פענוח JWT",
  "meta-tag-generator": "יצירת תגים",
  "robots-txt-generator": "יצירת robots.txt",
  "serp-preview": "תצוגת קטע",
  "hreflang-generator": "יצירת hreflang",
  percentage: "חשב",
  "vat-calculator": "חשב מע״מ",
  discount: "חשב הנחה",
  "profit-margin": "חשב מרווח",
  "bmi-calculator": "חשב BMI",
  "date-difference": "חשב הפרש",
  temperature: "המר",
  length: "המר",
  weight: "המר",
  "data-size": "המר",
  "hex-rgb-hsl": "המר צבע",
  "contrast-checker": "בדוק ניגודיות",
  "palette-generator": "צור פלטה",
  "password-generator": "צור סיסמאות",
  "qr-generator": "צור קוד QR",
  "random-string": "צור מחרוזות",
  "unix-timestamp": "המר חותמת זמן",
  "timezone-convert": "המר אזור זמן",
  "xml-formatter": "עיצוב XML",
  "yaml-json": "המר YAML",
  "sitemap-helper": "צור sitemap",
  "canonical-helper": "צור canonical",
  "schema-generator": "צור schema",
  "og-preview": "צור Open Graph",
  speed: "המר",
  area: "המר",
  volume: "המר",
  pressure: "המר",
  energy: "המר",
  duration: "המר",
  "gradient-generator": "צור CSS",
  "url-parser": "פרק URL",
  "query-parser": "פרק query",
  "invoice-math": "חשב חשבונית",
  "resume-bullets": "עצב נקודות",
  "cover-letter-template": "בנה תבנית",
  "ics-event": "צור ICS",
};

export const ACTION_LABELS: Record<Locale, Record<string, string>> = {
  en: EN,
  de: DE,
  uk: UK,
  pl: PL,
  fr: FR,
  es: ES,
  it: IT,
  pt: PT,
  nl: NL,
  tr: TR,
  ar: AR,
  he: HE,
};

export const ACTION_LABEL_EN = EN;
