/** Readable Freela sticker identity. Same id always draws the same mark. */

import { toolRegistry } from "@/data/tools";

export const MOTIFS = [
  "merge",
  "split",
  "rotate",
  "squeeze",
  "crop",
  "frame",
  "image",
  "grid",
  "lock",
  "qr",
  "swatch",
  "braces",
  "code",
  "hash",
  "link",
  "clock",
  "calc",
  "text",
  "check",
  "spark",
  "table",
  "mail",
  "globe",
  "list",
  "percent",
  "key",
  "eye",
  "pages",
  "count",
  "barcode",
  "swap",
] as const;

export type Motif = (typeof MOTIFS)[number];

export type StickerSpec = {
  id: string;
  motif: Motif;
  ink: number;
  /** Short action, drawn large. Whole words only. */
  action: string;
  /** Format or object, drawn under the action. */
  object: string;
};

const DROP = new Set([
  "online",
  "files",
  "file",
  "a",
  "the",
  "of",
  "to",
  "and",
  "from",
  "for",
  "with",
  "any",
  "two",
  "an",
  "or",
  "in",
  "on",
  "per",
  "each",
  "your",
]);

const ROLE = new Set([
  "generator",
  "converter",
  "calculator",
  "helper",
  "checker",
  "viewer",
  "formatter",
  "validator",
  "decoder",
  "encoder",
  "template",
  "status",
  "draft",
  "parser",
]);

/** Whole-word shorts. Never a mid-word slice. */
const SHORT: Record<string, string> = {
  extract: "PULL",
  validate: "CHECK",
  markdown: "MD",
  decimal: "DEC",
  builder: "BUILD",
  checksum: "SUM",
  convert: "TURN",
  counter: "COUNT",
  password: "PASS",
  reverse: "REV",
  canonical: "CANON",
  character: "CHARS",
  characters: "CHARS",
  compare: "DIFF",
  compress: "SHRINK",
  difference: "DIFF",
  duplicate: "DUPES",
  duplicates: "DUPES",
  extension: "EXT",
  favicon: "ICON",
  frequency: "FREQ",
  heading: "HEADS",
  headings: "HEADS",
  integer: "INT",
  interest: "RATE",
  keyword: "KEY",
  metadata: "META",
  normalize: "NORM",
  preview: "VIEW",
  relative: "REL",
  unicode: "UNI",
  address: "ADDR",
  average: "AVG",
  balance: "BAL",
  barcode: "BAR",
  base64url: "B64",
  basename: "BASE",
  breadcrumb: "CRUMB",
  business: "WORK",
  calendar: "CAL",
  comments: "NOTES",
  complementary: "OPP",
  compound: "COMP",
  contains: "HAS",
  contrast: "WCAG",
  degrees: "DEG",
  delimiter: "CHAR",
  density: "DENSE",
  description: "DESC",
  deviation: "STDEV",
  diacritics: "MARKS",
  dimensions: "SIZE",
  directory: "DIR",
  discount: "OFF",
  distance: "DIST",
  duration: "SPAN",
  entities: "ENTS",
  entropy: "BITS",
  estimate: "EST",
  explain: "WHY",
  expression: "EXPR",
  factorial: "FACT",
  factors: "FACTOR",
  fibonacci: "FIB",
  flatten: "FLAT",
  fraction: "FRAC",
  gradient: "GRAD",
  grayscale: "GRAY",
  hashtags: "TAGS",
  hreflang: "HREFL",
  initials: "INIT",
  invoice: "BILL",
  levenshtein: "EDIT",
  luminance: "LUM",
  manifest: "APP",
  meeting: "MEET",
  mentions: "MENT",
  minutes: "MINS",
  missing: "MISS",
  nearest: "NEAR",
  newlines: "NLS",
  noindex: "NOIDX",
  numbers: "NUMS",
  numerals: "ROMAN",
  outline: "TREE",
  overlay: "OVER",
  overtime: "OT",
  palette: "MIX",
  palindrome: "PAL",
  pattern: "SCAN",
  percentage: "PCT",
  pixelate: "PIXEL",
  pomodoro: "POMO",
  pressure: "PSI",
  printable: "QP",
  protect: "LOCK",
  punctuation: "PUNCT",
  pythagoras: "PYTH",
  quadratic: "QUAD",
  quarter: "QTR",
  radians: "RAD",
  readable: "INK",
  reading: "EASE",
  redirect: "REDIR",
  reorder: "ORDER",
  replace: "SWAP",
  resolve: "RESOLV",
  savings: "SAVE",
  sentence: "SENT",
  sequence: "SEQ",
  simplify: "SIMPLE",
  sitemap: "MAP",
  snippet: "SERP",
  standard: "STDEV",
  statistics: "STATS",
  temperature: "TEMP",
  timestamp: "STAMP",
  timezone: "ZONE",
  tracking: "UTM",
  trailing: "SLASH",
  transpose: "PIVOT",
  triangle: "TRI",
  truncate: "CUT",
  twitter: "CARD",
  unescape: "PLAIN",
  watermark: "STAMP",
  weekday: "DAY",
  whitespace: "SPACE",
  spaces: "SPACE",
  image: "IMG",
  images: "IMG",
  encode: "ENC",
  decode: "DEC",
  escape: "ESC",
  redact: "HIDE",
  remove: "DROP",
  delete: "DROP",
  empty: "EMPTY",
  pdf: "PDF",
  json: "JSON",
  csv: "CSV",
  xml: "XML",
  yaml: "YAML",
  html: "HTML",
  css: "CSS",
  url: "URL",
  urls: "URLS",
  hex: "HEX",
  rgb: "RGB",
  hsl: "HSL",
  cmyk: "CMYK",
  uuid: "UUID",
  ulid: "ULID",
  qr: "QR",
  jpg: "JPG",
  jpeg: "JPG",
  png: "PNG",
  webp: "WEBP",
  heic: "HEIC",
  ico: "ICO",
  docx: "DOCX",
  xlsx: "XLSX",
  excel: "XLSX",
  base64: "B64",
  jwt: "JWT",
  sha: "SHA",
  crc32: "CRC",
  iban: "IBAN",
  isbn: "ISBN",
  vat: "VAT",
  bmi: "BMI",
  roi: "ROI",
  cagr: "CAGR",
  csp: "CSP",
  mac: "MAC",
  pin: "PIN",
  sql: "SQL",
  ics: "ICS",
  exif: "EXIF",
  utm: "UTM",
  wcag: "WCAG",
  iso: "ISO",
  ipv4: "IPV4",
  ipv6: "IPV6",
  ndjson: "NDJSON",
  tsv: "TSV",
  rot13: "ROT13",
  rot47: "ROT47",
  gcd: "GCD",
  lcm: "LCM",
  px: "PX",
  pt: "PT",
  rem: "REM",
  mb: "MB",
  gb: "GB",
  ld: "LD",
  env: "ENV",
  cron: "CRON",
  slug: "SLUG",
  mime: "MIME",
  emails: "MAIL",
  email: "MAIL",
  phones: "PHONE",
  phone: "PHONE",
  pages: "PAGES",
  page: "PAGE",
  lines: "LINES",
  line: "LINE",
  words: "WORDS",
  word: "WORD",
  text: "TEXT",
  color: "COLOR",
  colors: "COLOR",
  number: "NUM",
  string: "TEXT",
  code: "CODE",
  tags: "TAGS",
  tag: "TAG",
  keys: "KEYS",
  key: "KEY",
  array: "ARRAY",
  binary: "BIN",
  width: "WIDTH",
  zero: "ZERO",
  https: "HTTPS",
  robots: "ROBOT",
  txt: "TXT",
  unit: "UNIT",
  units: "UNITS",
  data: "DATA",
  length: "LEN",
  weight: "MASS",
  speed: "SPEED",
  area: "AREA",
  volume: "VOL",
  energy: "NRG",
  query: "QUERY",
  path: "PATH",
  host: "HOST",
  domain: "DOMAIN",
  port: "PORT",
  origin: "ORIGIN",
  params: "PARMS",
  map: "MAP",
  info: "INFO",
  title: "TITLE",
  change: "DELTA",
  middle: "MID",
  order: "ORDER",
  dark: "DARK",
  goal: "GOAL",
  mean: "MEAN",
  median: "MEDIAN",
  ratio: "RATIO",
  week: "WEEK",
  days: "DAYS",
  date: "DATE",
  clock: "CLOCK",
  year: "YEAR",
  month: "MONTH",
  months: "MONTH",
  block: "BLOCK",
  blocks: "BLOKS",
  price: "PRICE",
  pay: "PAY",
  cost: "COST",
  loan: "LOAN",
  salary: "PAY",
  tip: "TIP",
  fuel: "FUEL",
  age: "AGE",
  hourly: "HOUR",
  rate: "RATE",
  simple: "SIMPLE",
  rule: "RULE",
  three: "THREE",
  even: "EVEN",
  break: "BREAK",
  roman: "ROMAN",
  prime: "PRIME",
  circle: "CIRC",
  aspect: "ASPECT",
  invert: "INVERT",
  mix: "MIX",
  random: "RAND",
  dummy: "DUMMY",
  dice: "DICE",
  roller: "ROLL",
  pick: "PICK",
  list: "LIST",
  score: "SCORE",
  mask: "MASK",
  hash: "HASH",
  force: "FORCE",
  dedent: "DEDENT",
  tabs: "TABS",
  join: "JOIN",
  filter: "FILTER",
  range: "RANGE",
  morse: "MORSE",
  cipher: "CIPHER",
  atbash: "ATBASH",
  strip: "STRIP",
  sort: "SORT",
  secret: "SECRET",
  pascal: "PASCAL",
  case: "CASE",
  column: "COL",
  row: "ROW",
  rows: "ROWS",
  count: "COUNT",
  top: "TOP",
  quoted: "QP",
  format: "FORMAT",
  syntax: "SYNTAX",
  header: "HEADER",
  basic: "BASIC",
  auth: "AUTH",
  subnet: "SUBNET",
  cidr: "CIDR",
  semver: "SEMVER",
  bump: "BUMP",
  faq: "FAQ",
  card: "CARD",
  alt: "ALT",
  ink: "INK",
  tint: "TINT",
  shade: "SHADE",
  name: "NAME",
  names: "NAMES",
  link: "LINK",
  links: "LINKS",
  toggle: "TOGGLE",
  slash: "SLASH",
  stats: "STATS",
  round: "ROUND",
  roots: "ROOTS",
  leap: "LEAP",
  end: "END",
  add: "ADD",
  web: "WEB",
  set: "SET",
  sizes: "SIZES",
  size: "SIZE",
  reader: "READ",
  event: "EVENT",
  bullets: "BULLET",
  bullet: "BULLET",
  letter: "LETTER",
  cover: "COVER",
  resume: "RESUME",
  open: "OPEN",
  graph: "GRAPH",
  schema: "SCHEMA",
  social: "SOCIAL",
  table: "TABLE",
  blur: "BLUR",
  video: "VIDEO",
  universal: "ANY",
  wrap: "WRAP",
  find: "FIND",
  repeat: "REPEAT",
  camel: "CAMEL",
  snake: "SNAKE",
  kebab: "KEBAB",
  toc: "TOC",
  cookie: "COOKIE",
  luhn: "LUHN",
  crc: "CRC",
  minify: "MIN",
  test: "TEST",
  pairs: "PAIRS",
  fib: "FIB",
  until: "UNTIL",
  from: "FROM",
  clean: "CLEAN",
  diff: "DIFF",
  meta: "META",
  serp: "SERP",
  profit: "MARGIN",
  margin: "MARGIN",
  unix: "UNIX",
  lorem: "LOREM",
  ipsum: "IPSUM",
  rotate: "TURN",
  flip: "FLIP",
  prefix: "PRE",
  suffix: "POST",
  caesar: "CAESAR",
  href: "HREF",
  hrefs: "HREFS",
  split: "SPLIT",
  flesch: "EASE",
  mailto: "MAILTO",
  pathname: "PATH",
  merge: "MERGE",
  crop: "CROP",
  resize: "SIZE",
  time: "TIME",
  shift: "SHIFT",
  ease: "EASE",
  scan: "SCAN",
  base: "BASE",
  dir: "DIR",
  flat: "FLAT",
  detect: "DETECT",
  drop: "DROP",
  delta: "DELTA",
  named: "NAMED",
  draft: "DRAFT",
  pixel: "PIXEL",
  gray: "GRAY",
  pretty: "PRETTY",
  new: "NEW",
  calc: "CALC",
  file: "FILE",
  img: "IMG",
  mail: "MAIL",
  stamp: "STAMP",
  mark: "MARK",
  turn: "TURN",
  shrink: "SHRINK",
  pull: "PULL",
  hide: "HIDE",
  check: "CHECK",
  jsonld: "LD",
  "json-ld": "LD",
};

const OVERRIDES: Record<string, [string, string]> = {
  "line-lengths": ["LINE", "LEN"],
  "mime-to-ext": ["FILE", "MIME"],
  "utf8-bytes": ["UTF", "BYTE"],
  "seconds-hms": ["SEC", "HMS"],
  "hms-seconds": ["HMS", "SEC"],
  "merge-pdf": ["MERGE", "PDF"],
  "split-pdf": ["SPLIT", "PDF"],
  "rotate-pdf": ["TURN", "PDF"],
  "reorder-pdf": ["ORDER", "PDF"],
  "compress-pdf": ["SHRINK", "PDF"],
  "compress-image": ["SHRINK", "IMG"],
  "images-to-pdf": ["IMG", "PDF"],
  "extract-pdf-pages": ["PULL", "PAGES"],
  "extract-pdf-text": ["PULL", "TEXT"],
  "delete-pdf-pages": ["DROP", "PAGES"],
  "pdf-to-image": ["PDF", "JPG"],
  "text-to-pdf": ["TEXT", "PDF"],
  "markdown-to-pdf": ["MD", "PDF"],
  "docx-to-pdf": ["DOCX", "PDF"],
  "heic-to-jpg": ["HEIC", "JPG"],
  "png-to-ico": ["PNG", "ICO"],
  "csv-json": ["CSV", "JSON"],
  "yaml-json": ["YAML", "JSON"],
  "json-to-yaml": ["JSON", "YAML"],
  "xlsx-csv": ["XLSX", "CSV"],
  "markdown-html": ["MD", "HTML"],
  "html-to-markdown": ["HTML", "MD"],
  "image-to-base64": ["IMG", "B64"],
  "base64-to-image": ["B64", "IMG"],
  "camel-snake": ["CAMEL", "SNAKE"],
  "snake-camel": ["SNAKE", "CAMEL"],
  "kebab-camel": ["KEBAB", "CAMEL"],
  "tabs-to-spaces": ["TABS", "SPACE"],
  "lines-to-csv": ["LINES", "CSV"],
  "tsv-to-csv": ["TSV", "CSV"],
  "ndjson-to-array": ["NDJSON", "ARRAY"],
  "array-to-ndjson": ["ARRAY", "NDJSON"],
  "binary-to-decimal": ["BIN", "DEC"],
  "hex-to-decimal": ["HEX", "NUM"],
  "decimal-binary": ["DEC", "BIN"],
  "ipv4-to-int": ["IPV4", "INT"],
  "int-to-ipv4": ["INT", "IPV4"],
  "fraction-to-decimal": ["FRAC", "DEC"],
  "deg-to-rad": ["DEG", "RAD"],
  "px-to-rem": ["PX", "REM"],
  "px-to-pt": ["PX", "PT"],
  "rgb-cmyk": ["RGB", "CMYK"],
  "json-env": ["JSON", "ENV"],
  "env-json": ["ENV", "JSON"],
  "hex-rgb-hsl": ["HEX", "RGB"],
  "word-counter": ["WORDS", "COUNT"],
  "character-counter": ["CHARS", "COUNT"],
  "remove-duplicate-lines": ["DROP", "DUPES"],
  "remove-empty-lines": ["DROP", "EMPTY"],
  "json-keys": ["JSON", "KEYS"],
  "json-sort-keys": ["SORT", "KEYS"],
  "og-preview": ["OG", "VIEW"],
  "convert-video": ["VIDEO", "NOTE"],
  "is-dark-hex": ["DARK", "HEX"],
  "social-counter": ["SOCIAL", "CHARS"],
  "csv-row-count": ["COUNT", "ROWS"],
  "roman-numeral": ["ROMAN", "NUM"],
  "average-mean": ["AVG", "MEAN"],
  "entropy-estimate": ["BITS", "EST"],
  "data-size": ["MB", "GB"],
  "strip-zero-width": ["DROP", "ZW"],
  "json-formatter": ["JSON", "PRETTY"],
  "xml-formatter": ["XML", "PRETTY"],
  "sql-formatter": ["SQL", "PRETTY"],
  "case-converter": ["CASE", "TEXT"],
  "uuid-generator": ["UUID", "NEW"],
  "password-generator": ["PASS", "NEW"],
  "qr-generator": ["QR", "CODE"],
  "barcode-generator": ["BAR", "CODE"],
  "pin-generator": ["PIN", "NEW"],
  "lorem-ipsum": ["LOREM", "TEXT"],
  "hash-generator": ["SHA", "HASH"],
  "ulid-generator": ["ULID", "NEW"],
  "cron-generator": ["CRON", "EXPR"],
  "gradient-generator": ["CSS", "GRAD"],
  "favicon-generator": ["ICON", "PNG"],
  "meta-tag-generator": ["META", "TAGS"],
  "robots-txt-generator": ["ROBOT", "TXT"],
  "hreflang-generator": ["HREFL", "TAG"],
  "schema-generator": ["LD", "JSON"],
  "palette-generator": ["COLOR", "MIX"],
  "timezone-convert": ["ZONE", "TIME"],
  "temperature": ["TEMP", "UNIT"],
  "length": ["LEN", "UNIT"],
  "weight": ["MASS", "UNIT"],
  "speed": ["SPEED", "UNIT"],
  "area": ["AREA", "UNIT"],
  "volume": ["VOL", "UNIT"],
  "pressure": ["PSI", "UNIT"],
  "energy": ["NRG", "UNIT"],
  "duration": ["TIME", "SPAN"],
  "percentage": ["PCT", "CALC"],
  "vat-calculator": ["VAT", "CALC"],
  "bmi-calculator": ["BMI", "CALC"],
  "tip-calculator": ["TIP", "CALC"],
  "loan-calculator": ["LOAN", "CALC"],
  "age-calculator": ["AGE", "CALC"],
  "cagr": ["CAGR", "CALC"],
  "factorial": ["FACT", "CALC"],
  "median-list": ["MEDIAN", "LIST"],
  "pythagoras": ["PYTH", "CALC"],
  "universal-converter": ["ANY", "FILE"],
  "base64": ["B64", "CODEC"],
  "url-codec": ["URL", "CODEC"],
  "file-extension": ["FILE", "EXT"],
  "flip-image": ["FLIP", "IMG"],
  "rotate-image": ["TURN", "IMG"],
  "crop-image": ["CROP", "IMG"],
  "resize-image": ["SIZE", "IMG"],
  "blur-image": ["BLUR", "IMG"],
  "image-grayscale": ["GRAY", "IMG"],
  "image-pixelate": ["PIXEL", "IMG"],
  "image-dimensions": ["DIMS", "IMG"],
  "image-text-overlay": ["TEXT", "IMG"],
  "pdf-watermark": ["STAMP", "PDF"],
  "pdf-page-numbers": ["NUMS", "PDF"],
  "pdf-password": ["LOCK", "PDF"],
  "pdf-metadata": ["META", "PDF"],
  "pdf-page-sizes": ["SIZE", "PDF"],
  "pdf-set-info": ["TITLE", "PDF"],
  "qr-reader": ["READ", "QR"],
  "exif-strip": ["DROP", "EXIF"],
  "whitespace-cleaner": ["CLEAN", "SPACE"],
  "sort-lines": ["SORT", "LINES"],
  "sort-words": ["SORT", "WORDS"],
  "count-lines": ["COUNT", "LINES"],
  "number-lines": ["NUM", "LINES"],
  "reverse-lines": ["REV", "LINES"],
  "reverse-text": ["REV", "TEXT"],
  "reverse-words": ["REV", "WORDS"],
  "join-lines": ["JOIN", "LINES"],
  "filter-lines": ["FILTER", "LINES"],
  "split-delimiter": ["SPLIT", "CHAR"],
  "find-replace": ["FIND", "SWAP"],
  "extract-emails": ["PULL", "MAIL"],
  "extract-urls": ["PULL", "URLS"],
  "extract-phones": ["PULL", "PHONE"],
  "extract-hashtags": ["PULL", "TAGS"],
  "extract-mentions": ["PULL", "MENT"],
  "extract-ipv4": ["PULL", "IPV4"],
  "extract-hex-colors": ["PULL", "HEX"],
  "extract-iso-dates": ["PULL", "DATES"],
  "extract-domain": ["PULL", "HOST"],
  "redact-emails": ["HIDE", "MAIL"],
  "redact-phones": ["HIDE", "PHONE"],
  "redact-ipv4": ["HIDE", "IPV4"],
  "slug-generator": ["SLUG", "URL"],
  "slug-from-url": ["URL", "SLUG"],
  "slug-each-line": ["SLUG", "LINE"],
  "word-frequency": ["WORD", "FREQ"],
  "letter-frequency": ["LETTER", "FREQ"],
  "text-statistics": ["TEXT", "STATS"],
  "text-diff": ["TEXT", "DIFF"],
  "json-validator": ["JSON", "CHECK"],
  "json-escape": ["JSON", "ESC"],
  "json-flatten": ["FLAT", "JSON"],
  "json-array-length": ["JSON", "LEN"],
  "json-duplicate-keys": ["DUPES", "JSON"],
  "csv-transpose": ["PIVOT", "CSV"],
  "csv-pick-column": ["COL", "CSV"],
  "csv-width-check": ["WIDTH", "CSV"],
  "html-minify": ["MIN", "HTML"],
  "css-minify": ["MIN", "CSS"],
  "html-entities": ["HTML", "ENTS"],
  "strip-html": ["DROP", "HTML"],
  "html-tag-balance": ["BAL", "HTML"],
  "regex-tester": ["REGEX", "TEST"],
  "regex-escape": ["REGEX", "ESC"],
  "jwt-decoder": ["JWT", "READ"],
  "uuid-validate": ["UUID", "CHECK"],
  "ulid-validate": ["ULID", "CHECK"],
  "hash-line": ["HASH", "LINE"],
  "crc32-hash": ["CRC", "SUM"],
  "morse-encode": ["MORSE", "ENC"],
  "morse-decode": ["MORSE", "DEC"],
  "hex-encode": ["HEX", "ENC"],
  "hex-decode": ["HEX", "DEC"],
  "binary-encode": ["BIN", "ENC"],
  "rot13": ["ROT13", "TEXT"],
  "caesar-shift": ["CAESAR", "TEXT"],
  "atbash-cipher": ["ATBASH", "TEXT"],
  "rot47-cipher": ["ROT47", "TEXT"],
  "palindrome-check": ["PAL", "CHECK"],
  "force-https": ["FORCE", "HTTPS"],
  "utm-builder": ["UTM", "URL"],
  "mailto-builder": ["MAIL", "LINK"],
  "query-build": ["QUERY", "BUILD"],
  "query-parser": ["QUERY", "READ"],
  "query-drop-key": ["DROP", "QUERY"],
  "url-parser": ["URL", "READ"],
  "url-origin": ["URL", "HOST"],
  "url-pathname": ["URL", "PATH"],
  "resolve-relative-url": ["REL", "URL"],
  "sort-query": ["SORT", "QUERY"],
  "toggle-trailing-slash": ["SLASH", "URL"],
  "strip-utm": ["DROP", "UTM"],
  "canonical-helper": ["CANON", "URL"],
  "canonical-host": ["CANON", "HOST"],
  "sitemap-helper": ["MAP", "XML"],
  "serp-preview": ["SERP", "VIEW"],
  "meta-length": ["META", "LEN"],
  "meta-robots": ["ROBOT", "META"],
  "heading-outline": ["HEADS", "TREE"],
  "heading-order": ["HEADS", "ORDER"],
  "missing-alt": ["MISS", "ALT"],
  "noindex-detect": ["NOIDX", "FIND"],
  "keyword-density": ["KEY", "DENSE"],
  "keyword-in-title": ["KEY", "TITLE"],
  "title-length": ["TITLE", "LEN"],
  "empty-link-check": ["EMPTY", "LINK"],
  "href-extract": ["PULL", "HREF"],
  "robots-path-test": ["ROBOT", "PATH"],
  "twitter-card": ["CARD", "TAGS"],
  "breadcrumb-ld": ["CRUMB", "LD"],
  "faq-jsonld": ["FAQ", "LD"],
  "redirect-pairs": ["REDIR", "CSV"],
  "domain-syntax": ["DOMAIN", "CHECK"],
  "port-from-url": ["PORT", "URL"],
  "email-syntax": ["MAIL", "CHECK"],
  "iban-check": ["IBAN", "SUM"],
  "isbn-check": ["ISBN", "SUM"],
  "luhn-check": ["LUHN", "SUM"],
  "ipv4-validate": ["IPV4", "CHECK"],
  "ipv6-validate": ["IPV6", "CHECK"],
  "cron-validate": ["CRON", "CHECK"],
  "cron-explain": ["CRON", "WHY"],
  "semver-validate": ["SEMVER", "CHECK"],
  "semver-compare": ["SEMVER", "DIFF"],
  "semver-bump": ["SEMVER", "BUMP"],
  "iso-date-validate": ["ISO", "CHECK"],
  "yaml-top-keys": ["YAML", "KEYS"],
  "quoted-printable": ["QP", "TEXT"],
  "mac-format": ["MAC", "ADDR"],
  "cidr-contains": ["CIDR", "HAS"],
  "subnet-info": ["SUBNET", "INFO"],
  "basic-auth-header": ["AUTH", "HEADER"],
  "cookie-parse": ["COOKIE", "READ"],
  "mime-guess": ["MIME", "EXT"],
  "levenshtein": ["EDIT", "DIST"],
  "strip-comments": ["DROP", "NOTES"],
  "dummy-json": ["DUMMY", "JSON"],
  "dummy-csv": ["DUMMY", "CSV"],
  "dice-roller": ["DICE", "ROLL"],
  "pick-from-list": ["PICK", "LIST"],
  "password-score": ["PASS", "SCORE"],
  "mask-center": ["MASK", "MID"],
  "random-string": ["RAND", "TEXT"],
  "random-number": ["RAND", "NUM"],
  "random-hex": ["RAND", "HEX"],
  "unix-timestamp": ["UNIX", "TIME"],
  "date-difference": ["DATE", "DIFF"],
  "add-days": ["ADD", "DAYS"],
  "days-until": ["DAYS", "LEFT"],
  "days-in-month": ["DAYS", "MONTH"],
  "add-months": ["ADD", "MONTH"],
  "end-of-month": ["END", "MONTH"],
  "add-clock": ["ADD", "MINS"],
  "clock-difference": ["CLOCK", "DIFF"],
  "pomodoro-blocks": ["POMO", "BLOKS"],
  "leap-year": ["LEAP", "YEAR"],
  "weekday-of": ["DAY", "DATE"],
  "iso-week": ["ISO", "WEEK"],
  "year-quarter": ["YEAR", "QTR"],
  "business-days": ["WORK", "DAYS"],
  "format-date": ["DATE", "TEXT"],
  "invert-hex": ["INVERT", "HEX"],
  "mix-hex": ["MIX", "HEX"],
  "complementary-hex": ["OPP", "HEX"],
  "tint-hex": ["TINT", "HEX"],
  "shade-hex": ["SHADE", "HEX"],
  "nearest-named-color": ["NEAR", "COLOR"],
  "readable-ink": ["INK", "COLOR"],
  "relative-luminance": ["LUM", "COLOR"],
  "color-extract": ["PULL", "COLOR"],
  "contrast-checker": ["WCAG", "COLOR"],
  "csp-builder": ["CSP", "BUILD"],
  "web-manifest": ["WEB", "APP"],
  "number-to-words": ["NUM", "WORDS"],
  "unit-price": ["UNIT", "PRICE"],
  "roi-calculator": ["ROI", "DELTA"],
  "meeting-cost": ["MEET", "COST"],
  "overtime-pay": ["OT", "PAY"],
  "simple-interest": ["SIMPLE", "RATE"],
  "compound-interest": ["COMP", "RATE"],
  "profit-margin": ["MARGIN", "CALC"],
  "discount": ["OFF", "CALC"],
  "fuel-cost": ["FUEL", "COST"],
  "salary-converter": ["PAY", "UNIT"],
  "hourly-rate": ["HOUR", "PAY"],
  "rule-of-three": ["RULE", "THREE"],
  "break-even": ["EVEN", "UNITS"],
  "savings-goal": ["SAVE", "GOAL"],
  "gcd-lcm": ["GCD", "LCM"],
  "prime-check": ["PRIME", "CHECK"],
  "prime-factors": ["PRIME", "FACTOR"],
  "quadratic-roots": ["QUAD", "ROOTS"],
  "stdev-list": ["STDEV", "LIST"],
  "range-stats": ["RANGE", "STATS"],
  "round-number": ["ROUND", "NUM"],
  "aspect-ratio": ["ASPECT", "RATIO"],
  "ratio-simplify": ["SIMPLE", "RATIO"],
  "triangle-area": ["TRI", "AREA"],
  "circle-math": ["CIRC", "AREA"],
  "invoice-math": ["BILL", "MATH"],
  "resume-bullets": ["RESUME", "BULLET"],
  "cover-letter-template": ["COVER", "LETTER"],
  "ics-event": ["ICS", "EVENT"],
  "table-markdown": ["TABLE", "MD"],
  "markdown-toc": ["MD", "TOC"],
  "prefix-suffix": ["PRE", "POST"],
  "wrap-text": ["WRAP", "TEXT"],
  "repeat-text": ["REPEAT", "TEXT"],
  "truncate-text": ["CUT", "TEXT"],
  "name-initials": ["NAME", "INIT"],
  "remove-punctuation": ["DROP", "PUNCT"],
  "remove-diacritics": ["DROP", "MARKS"],
  "sentence-per-line": ["SENT", "LINE"],
  "dedent-text": ["DEDENT", "TEXT"],
  "line-range": ["LINE", "RANGE"],
  "unicode-escape": ["UNI", "ESC"],
  "unicode-unescape": ["UNI", "PLAIN"],
  "normalize-newlines": ["NORM", "NLS"],
  "flesch-ease": ["EASE", "READ"],
  "secret-scan": ["SECRET", "SCAN"],
  "pascal-case": ["PASCAL", "CASE"],
  "path-basename": ["PATH", "BASE"],
  "path-dirname": ["PATH", "DIR"],
  "xml-escape": ["XML", "ESC"],
  "video-file-info": ["VIDEO", "INFO"],
  "convert-image": ["IMG", "WEBP"],
};

function fnv(text: string) {
  let h = 2166136261;
  for (let i = 0; i < text.length; i++) {
    h ^= text.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

function wordLabel(word: string) {
  const key = word.toLowerCase();
  if (SHORT[key]) return SHORT[key];
  if (key.length <= 6 && /^[a-z0-9]+$/i.test(key)) return key.toUpperCase();
  return "";
}

function nameTokens(name: string) {
  return name
    .toLowerCase()
    .split(/[^a-z0-9+]+/)
    .filter((word) => word && !DROP.has(word))
    .map((word) => ({ raw: word, label: wordLabel(word), role: ROLE.has(word) }))
    .filter((token) => token.label);
}

function motifFor(id: string, category: string): Motif {
  const parts = new Set(id.split("-"));
  const has = (...names: string[]) => names.some((name) => parts.has(name));
  if (id.startsWith("merge-")) return "merge";
  if (["split-pdf", "extract-pdf-pages", "delete-pdf-pages", "reorder-pdf", "line-range", "split-delimiter"].includes(id)) return "split";
  if (has("rotate") || id === "flip-image") return "rotate";
  if (has("compress", "minify")) return "squeeze";
  if (has("crop")) return "crop";
  if (has("resize", "dimensions", "favicon") || id === "png-to-ico" || id === "aspect-ratio") return "frame";
  if (has("pixelate", "grayscale", "blur", "overlay", "exif") || ["convert-image", "heic-to-jpg", "color-extract"].includes(id)) return "image";
  if (id.startsWith("qr-")) return "qr";
  if (has("barcode")) return "barcode";
  if (id.includes("counter") || ["count-lines", "word-frequency", "letter-frequency", "csv-row-count", "csv-width-check"].includes(id)) return "count";
  if (id === "pdf-password" || id === "force-https" || has("redact") || ["secret-scan", "mask-center", "strip-zero-width", "strip-comments"].includes(id)) return "lock";
  if (id === "password-generator" || has("iban", "isbn", "luhn") || id.endsWith("-validate") || ["palindrome-check", "crc32-hash", "prime-check", "contrast-checker"].includes(id)) return "check";
  if (has("json", "yaml", "xml", "csv", "tsv", "ndjson") || ["cookie-parse", "sql-formatter", "env-json", "json-env"].includes(id)) return "braces";
  if (id.includes("pdf")) return "pages";
  if (has("image", "png", "jpg", "jpeg", "webp", "heic", "ico")) return "image";
  if (has("regex", "cron", "semver", "html", "css", "markdown", "csp") || id === "web-manifest") return "code";
  if (has("hash", "base64", "base64url", "uuid", "ulid", "jwt", "morse", "cipher", "rot13", "rot47", "atbash", "caesar", "binary") || ["hex-encode", "hex-decode", "hex-to-decimal", "binary-encode", "decimal-binary", "binary-to-decimal"].includes(id)) return "hash";
  if (has("url", "slug", "domain", "mailto", "query", "sitemap", "robots", "meta", "heading", "noindex", "canonical", "hreflang", "og", "twitter", "breadcrumb", "utm", "href", "keyword", "redirect", "port")) return "link";
  if (has("date", "clock", "month", "months", "year", "leap", "pomodoro", "weekday", "days", "unix", "timezone", "duration") || ["business-days", "iso-week", "format-date", "add-days", "add-months", "days-until", "days-in-month"].includes(id)) return "clock";
  if (has("percent", "percentage", "roi", "price", "pay", "cost", "loan", "interest", "overtime", "meeting", "vat", "discount", "profit", "bmi", "salary", "tip", "fuel", "invoice", "cagr", "hourly", "savings") || ["break-even", "unit-price", "rule-of-three"].includes(id)) return "calc";
  if (has("color", "tint", "shade", "luminance", "palette", "hex") || ["invert-hex", "mix-hex", "is-dark-hex", "complementary-hex", "random-hex", "readable-ink", "nearest-named-color", "hex-rgb-hsl", "rgb-cmyk"].includes(id)) return "swatch";
  if (has("mail", "email", "phones", "emails")) return "mail";
  if (has("table", "column")) return "table";
  if (id.startsWith("sort-") || ["filter-lines", "pick-from-list"].includes(id)) return "list";
  if (has("ipv4", "ipv6", "cidr", "subnet", "mac")) return "globe";
  if (has("prime", "fraction", "stdev", "quadratic", "median", "gcd", "lcm", "factorial", "fibonacci", "average", "pythagoras", "triangle", "circle", "ratio", "roman") || ["deg-to-rad", "px-to-rem", "px-to-pt", "number-to-words", "range-stats", "round-number"].includes(id)) return "percent";
  if (has("word", "sentence", "text", "case", "line", "lines", "wrap", "reverse", "truncate", "repeat", "camel", "snake", "kebab", "dedent", "tabs", "join", "diacritics", "unicode", "normalize", "flesch", "punctuation", "initials", "lorem", "prefix", "whitespace")) return "text";
  if (category === "pdf-documents") return "pages";
  if (category === "images") return "image";
  if (category === "text") return "text";
  if (category === "developer") return "code";
  if (category === "seo") return "link";
  if (category === "calculators") return "calc";
  if (category === "converters") return "swap";
  if (category === "color") return "swatch";
  if (category === "generators") return "spark";
  if (category === "date-time") return "clock";
  return "spark";
}

function baseLabels(id: string, name: string) {
  const fixed = OVERRIDES[id];
  if (fixed) return { action: fixed[0], object: fixed[1], extras: [] as string[] };
  const tokens = nameTokens(name).filter((token) => !token.role);
  const labels: string[] = [];
  for (const token of tokens) {
    if (!labels.includes(token.label)) labels.push(token.label);
  }
  if (labels.length === 0) {
    for (const part of id.split("-")) {
      const label = wordLabel(part);
      if (label && !labels.includes(label)) labels.push(label);
    }
  }
  const action = labels[0] || "TOOL";
  const object = labels[1] || "TOOL";
  return { action, object, extras: labels.slice(2) };
}

type Draft = {
  id: string;
  category: string;
  motif: Motif;
  ink: number;
  action: string;
  object: string;
  extras: string[];
};

function buildSpecs() {
  const specs = new Map<string, StickerSpec>();
  const used = new Set<string>();
  const drafts: Draft[] = toolRegistry
    .filter((tool) => tool.status === "published")
    .map((tool) => {
      const name = tool.copy.en?.name ?? tool.id;
      const labels = baseLabels(tool.id, name);
      return {
        id: tool.id,
        category: tool.category,
        motif: motifFor(tool.id, tool.category),
        ink: fnv(tool.id) % 4,
        action: labels.action,
        object: labels.object,
        extras: labels.extras,
      };
    });

  for (const draft of drafts) {
    let object = draft.object;
    let action = draft.action;
    const options = [object, ...draft.extras.filter((extra) => extra !== action && extra !== object)];
    let index = 0;
    let key = `${draft.motif}|${action}|${object}`;
    while (used.has(key) && index < options.length) {
      object = options[index] || object;
      index += 1;
      key = `${draft.motif}|${action}|${object}`;
    }
    let salt = 0;
    while (used.has(key)) {
      salt += 1;
      const bit = draft.id.split("-").find((part) => {
        const label = wordLabel(part);
        return label && label !== action && label !== object;
      });
      object = (bit ? wordLabel(bit) : action).slice(0, 4) + String(salt);
      key = `${draft.motif}|${action}|${object}`;
      if (salt > 6) break;
    }
    used.add(key);
    specs.set(draft.id, {
      id: draft.id,
      motif: draft.motif,
      ink: draft.ink,
      action,
      object,
    });
  }
  return specs;
}

const SPECS = buildSpecs();

export function motifForId(id: string): Motif {
  return SPECS.get(id)?.motif ?? motifFor(id, "");
}

export function stickerSpec(id: string): StickerSpec {
  const known = SPECS.get(id);
  if (known) return known;
  const labels = baseLabels(id, id);
  return {
    id,
    motif: motifFor(id, ""),
    ink: fnv(id) % 4,
    action: labels.action,
    object: labels.object,
  };
}

export function stickerFingerprint(id: string) {
  const spec = stickerSpec(id);
  return `${spec.motif}|${spec.action}|${spec.object}`;
}
