export const PACK_TOOL_IDS = [
  "pdf-to-image",
  "heic-to-jpg",
  "docx-to-pdf",
  "pdf-watermark",
  "pdf-page-numbers",
  "pdf-password",
  "pdf-signature",
  "background-remover",
  "qr-reader",
  "barcode-generator",
  "tip-calculator",
  "loan-calculator",
  "compound-interest",
  "salary-converter",
  "age-calculator",
  "fuel-cost",
  "xlsx-csv",
  "markdown-html",
  "lorem-ipsum",
  "social-counter",
  "strip-html",
  "table-markdown",
  "cron-generator",
  "sql-formatter",
  "image-text-overlay",
  "image-blur",
  "png-to-ico",
  "universal-converter",
  "video-file-info",
  "convert-video",
  "text-to-pdf",
  "markdown-to-pdf",
  "extract-pdf-text",
  "video-to-mp4",
  "video-to-webm",
  "video-to-gif",
  "video-to-mp3",
  "audio-converter",
  "compress-video",
  "trim-video",
  "resize-video",
  "image-upscaler",
  "word-html-cleaner",
  "clipboard-list-helper",
] as const;

export type PackToolId = (typeof PACK_TOOL_IDS)[number];

export function isPackTool(id: string): id is PackToolId {
  return (PACK_TOOL_IDS as readonly string[]).includes(id);
}

export const PACK_BROWSER_WORKFLOWS = new Set<string>([
  "pdf-to-image",
  "heic-to-jpg",
  "qr-reader",
  "barcode-generator",
  "image-text-overlay",
  "image-blur",
  "png-to-ico",
  "universal-converter",
  "video-file-info",
  "extract-pdf-text",
  "video-to-mp4",
  "video-to-webm",
  "video-to-gif",
  "video-to-mp3",
  "audio-converter",
  "compress-video",
  "trim-video",
  "resize-video",
  "image-upscaler",
  "word-html-cleaner",
  "clipboard-list-helper",
]);
